platform :ios,'8.0'
use_frameworks!

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end

target "Meet" do
    pod 'SDWebImage', '~>3.7'
    pod 'AFNetworking'
    pod 'FMDB'
    pod 'SQLCipher', '~> 3.3.1'
    pod 'MJRefresh'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'Masonry'
    pod 'pop', '~> 1.0.9'
    pod 'SnapKit'
    pod 'IQKeyboardManager'
    pod 'Qiniu', :git => 'https://github.com/qiniu/objc-sdk.git', :branch => 'AFNetworking-3.x'
    pod 'MJExtension'
    pod 'AMapLocation' #定位SDK
    pod 'SDCycleScrollView','~> 1.64'
    pod 'NJKWebViewProgress'
    pod 'FDFullscreenPopGesture', '1.1'
    pod 'DZNEmptyDataSet'
    pod 'HyphenateSDK'
    pod 'MBProgressHUD'
    pod 'PLMediaStreamingKit'
#    pod 'PLPlayerKit'

end
